#!/usr/bin/env python3
import urllib.request
import urllib.parse
import json, os, sys, time
import parse_iheart_json

def main():
    if len(sys.argv) == 1:
        print('iheart-pyradio.py <space seperated list of station ids>')
    else:
        f = open(os.path.expanduser('~/.config/pyradio/stations.csv'), 'w')

        for i in sys.argv:
            try:
                station = parse_iheart_json.station_info (i)
                station_url = parse_iheart_json.get_station_url (station)
                f.write('"%s %s %s", "%s"\n' % (station['name'], station['callLetters'], 
                        station['markets'][0]['city'] + ", " + station['markets'][0]['stateAbbreviation'] + 
                        ", " + station['markets'][0]['country'], station_url))
                time.sleep (1);
            except:
                pass
        f.close()

if __name__ == "__main__":
    main()

